### PR TITLE
Fixes #55

### LINKED ISSUE #55: ClassCastException when using incorrect NBT values
Looking at the code it seems like there could be several ClassCastExceptions when using unexpected NBT types, for instance [here](https://github.com/wizards-of-lua/wizards-of-lua/blob/master/src/main/java/net/wizardsoflua/lua/nbt/NbtConverter.java#L101).
It would be better to use something similar to the class [LuaPreconditions](https://github.com/wizards-of-lua/wizards-of-lua/blob/prototype/src/main/java/net/karneim/luamod/lua/util/LuaPreconditions.java#L16-L20) to throw an understandable Exception that includes the full path to the incorrect NBT.

### PR DESCRIPTION
**Pull request by Adrodoc55**
Fixes #55

### CODE REVIEW

File: src/test/java/net/wizardsoflua/lua/nbt/NbtConverterTest.java [hunk 1]
```diff
@@ -0,0 +1,220 @@
...
+    // When:
+    NBTTagCompound actual = underTest.merge(nbt, data);
+
+    // Then:
+    assertThat(actual.getKeySet()).containsOnly(key);
+    assertThat(actual.getTag(key)).isEqualTo(new NBTTagShort((short) newValue));
+  }
+
+  @Test
+  public void test_merge__Kann_neuen_Tag_erzeugen() {
```
Comment (mkarneim) [inline src/test/java/net/wizardsoflua/lua/nbt/NbtConverterTest.java]: @Adrodoc55 I think it's better to use english here...
